name: autocopy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  autocopy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          echo "$MY_PAT"
      - name: checkout primary repo
        uses: actions/checkout@master
      - name: clone secondary repo
        run: |
          cd /home/runner/work
          mkdir missions
          git clone https://${{ secrets.MY_PAT }}@github.com/asa-niki/asa_missions.git /home/runner/work/missions
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} 
