name: autocopy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  autocopy:
    runs-on: ubuntu-latest
    steps:
      - name: clone booth repos
        uses: actions/checkout@master
        with:
            repository: asa-niki/asa_missions
            token: ${{ secrets.my_pat }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
