name: autocopy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  autocopy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          echo "$MY_PAT"
      - name: checkout primary repo
        uses: actions/checkout@master
      - name: clone secondary repo
        run: |
          cd /home/runner/work
          mkdir missions
          git clone https://${{ secrets.MY_PAT }}@github.com/asa-niki/asa_missions.git /home/runner/work/missions
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Copy source folder to target directories
        run: |
          # Folder to copy (source folder)
          SOURCE_FOLDER="your_source_folder"

          # Check if source folder exists
          if [ ! -d "$SOURCE_FOLDER" ]; then
              echo "Source folder '$SOURCE_FOLDER' does not exist!"
              exit 1
          fi

          # Loop through directories that match "NUMBER NUMBER _"
          for TARGET_FOLDER in [0-9][0-9]_*; do
              if [ -d "$TARGET_FOLDER" ]; then
                  echo "Copying '$SOURCE_FOLDER' to '$TARGET_FOLDER'..."
                  cp -r "$SOURCE_FOLDER" "$TARGET_FOLDER"
              else
                  echo "No valid target folder found."
              fi
          done

          echo "Copying complete!"