name: autocopy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  autocopy:
    runs-on: ubuntu-latest
    steps:
      - name: clone booth repos
        uses: actions/checkout@master
      - name: pull primary repo
        run: git clone https://asa-niki:${{secrets.MY_PAT}}@github.com/asa-niki/asa_missions.git
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
